name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Stats
        env:
          GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl -o github_stats.svg "https://github-readme-stats.vercel.app/api?username=kehman18&show_icons=true&count_private=true&include_all_commits=true&theme=radical&token=${{ secrets.GH_STATS_TOKEN }}"
          curl -o github_streak.svg "https://streak-stats.demolab.com/?user=kehman18&theme=radical&token=${{ secrets.GH_STATS_TOKEN }}"

      - name: Commit updated stats
        run: |
          git config --global user.name "kehman18"
          git config --global user.email "kehindeadekola96@gmail.com"
          git add github_stats.svg github_streak.svg
          git commit -m "Update GitHub stats"
          git push
